#!/bin/bash
# Modified blurlock so that it doesn't beep constantly

#Pauses sconsify
#pgrep sconsify && sconsify -command pause

# take screenshot
import -silent -window root /tmp/screenshot.png

# blur it
convert /tmp/screenshot.png -blur 0x15 /tmp/screenshotblur.png
rm /tmp/screenshot.png

# lock the screen
i3lock -e -i /tmp/screenshotblur.png

# sleep 1 adds a small delay to prevent possible race conditions with suspend
sleep 1

exit 0
