#! /bin/bash
# Pass a domain name as an argument (e.g. getip www.google.com)
# returns the IP address and domain for use in the /etc/hosts file
I=$(ping -4 -c 1 $1 | grep "bytes from"| awk -F"[()]" '{print $2}')
echo $I	$1
