#! /bin/bash



#============================================
# Creates an enumerated menu of active tmux 
# sessions, and connects to user selected 
# Session.
#============================================



# Set up temporary file
TLS=~/.cache/list_tmp.sh
LIST=~/.cache/list_tmp.txt
rm $TLS
touch $TLS

# main loop of generated script
echo "#!/bin/bash" >> $TLS
echo "EXIT=0" >> $TLS
echo "while [ \$EXIT == 0 ]" >> $TLS
echo "do" >> $TLS
echo "clear" >> $TLS
echo "echo SELECT SESSION" >> $TLS
echo "echo ''" >> $TLS

# Read active tmux sessions into script to display in menu
tmux ls > $LIST || exit 1
COUNT=1
while read SES
#for SES in ($LIST)
do
	echo "echo $COUNT: ${SES%%:*} " >> $TLS
	COUNT=$(( $COUNT + 1 ))
done <$LIST

# Handiling for 0 or 1 active sessions
if [ $COUNT -eq 2 ] ; then
	tmux attach
	exit
elif [ $COUNT -eq 1 ] ; then
	exit
fi
# Set up case selection
echo "read n" >> $TLS
echo "case \$n in" >> $TLS

# Read active tmux sessions into script for case selection
COUNT=1
while read SES 
do
	echo "	$COUNT)	SEL=${SES%%:*}" >> $TLS
	echo "		EXIT=1" >> $TLS
	echo "		;;" >> $TLS
	COUNT=$(( COUNT + 1 ))
done <$LIST
echo "*)	echo Invalid Selection" >> $TLS
echo "          EXIT=1" >> $TLS
echo "		;;" >> $TLS
echo "esac" >> $TLS

# Close out while loop and connect to session
echo "done" >> $TLS
echo "tmux a -t \$SEL" >> $TLS

# Make script executable, remove temorary file, run new script
chmod +x $TLS
rm $LIST
$TLS

